-- Log de ações executadas pela IA (Nerve Center)
create table if not exists public.ai_action_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  action_type text not null,
  status text not null,
  payload jsonb,
  result jsonb,
  error text,
  screen text,
  source text not null default 'nerve_center'
);

create index if not exists ai_action_logs_created_at_idx on public.ai_action_logs (created_at desc);
create index if not exists ai_action_logs_action_type_idx on public.ai_action_logs (action_type);
